version: '3'

// TODO: add wings and pterodactyl
services:

  controlpanel_standalone:
    build:
      context: ../../
      dockerfile: ./docker/standalone/Dockerfile
    container_name: controlpanel_standalone
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './website_files:/var/www/html:rw' # change it to your project
      - './nginx_config:/etc/nginx/conf.d/:rw' # change it
    networks:
      - laravel

  mysql:
    image: mysql
    container_name: controlpanel_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: controlpanel
      MYSQL_USER: controlpanel
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "mysql:/var/lib/mysql:delegated"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: controlpanel_phpmyadmin
    depends_on:
      - mysql
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=controlpanel_mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_ARBITRARY=1
    networks:
      - laravel

  redis:
    image: redis
    container_name: controlpanel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
