
version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - ctrlpanel
    volumes:
      - app:/var/www/html

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ctrlpanel
      MYSQL_USER: ctrlpanel
      MYSQL_PASSWORD: ctrlpanel
    networks:
      - ctrlpanel
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    networks:
      - ctrlpanel
    volumes:
      - redis:/data

networks:
  ctrlpanel:
    driver: bridge

volumes:
    app:
    mysql:
    redis: