version: '3'

networks:
  laravel:

services:
  nginx:
    build:
      dockerfile: DockerfileNGINX
    container_name: ctrlpanel_nginx
    ports:
      - 80:81
    volumes:
      - "../:/var/www/html"
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql
    container_name: ctrlpanel_mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ctrlpanel
      MYSQL_USER: ctrlpanel
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "mysql:/var/lib/mysql:delegated"
    networks:
      - laravel
  redis:
    image: redis:alpine
    networks:
      - laravel

  php:
    build:
      dockerfile: DockerfilePHP
    container_name: ctrlpanel_php
    volumes:
      - "../:/var/www/html"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ctrlpanel_phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOST=ctrlpanel_mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_ARBITRARY=1
    networks:
      - laravel

volumes:
  mysql:
